### ISSUE TITLE
"Without browserify" example does not work

### ISSUE THREAD

**Issue by kannes** [scottglz/image-outline#2]
The example did not work for me. I had to use image.src instead of image.href and do that after the onload. I have no clue about Javascript but maybe use this instead:

    // Get your hands on a loaded HTMLImageElement, preferably one showing a PNG, 
    // with a transparent background, maybe of a cow.  
    var image = new Image();
    image.onload = function() {
        var polygon = getImageOutline(image);
        // polygon is now an array of {x,y} objects. Have fun!
    };
    image.src = 'http://www.cow.pics/cow.png';

**Comment by scottglz** [comment]
Thanks, changed.
